In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()       # 그래프 만들지말고 바로 결과값 반환 실행

In [2]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]            
], dtype="float32")

y = np.array([
    [0.],
    [0.],
    [0.],
    [1.]
], dtype="float32")

In [3]:
w = np.array([[1], [2]], dtype="float32")

b = np.array([3], dtype="float32")

In [4]:
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [5]:
learning_rate = 0.01

for i in range(10000):
    hypothesis = sigmoid(np.dot(X, w) + b)

    cost = np.sum(-1/4 * (y*np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis)))
    
    X_col_2d0 = X.T[0].reshape(1, -1)
    w0_grad = 1/4 * np.sum(np.dot(X_col_2d0, (hypothesis - y)))
    w0_new = w[0]-learning_rate * w0_grad
    
    X_col_2d1 = X.T[1].reshape(1, -1)
    w1_grad = 1/4 * np.sum(np.dot(X_col_2d1, (hypothesis - y)))
    w1_new = w[1]-learning_rate * w1_grad
    
    b_grad = 1/4 * np.sum(hypothesis - y)
    
    b_new = b - learning_rate * b_grad
    
    w[0] = w0_new
    w[1] = w1_new
    b = b_new
    
    if (i+1) % 100 == 0:
        #print("epoch[{0:>4}]  w[0]= {1}, w[1]= {2}, b= {3:6.4f}, e={4:6.5f}".format(i+1, w[0], w[1], b, cost))
        print("epoch [%5d]  w[0]: %7.4f,  w[1]: %7.4f,  b: %7.4f,  e: %7.4f"  %(i+1, w[0], w[1], b, cost))
        # numpy class type 들은 format 함수를 활용해서 형식 지정을 할 수 없다. !!!
print("\n--------------------------------")
print("\n\t[result]")
print("\tw0 = %7.4f" %w[0])
print("\tw1 = %7.4f" %w[1])
print("\tb = %7.4f" %b)
print("\terror = %7.4f" %cost)

epoch [  100]  w[0]:  0.7586,  w[1]:  1.7540,  b:  2.2784,  e:  2.3857
epoch [  200]  w[0]:  0.5306,  w[1]:  1.5149,  b:  1.5894,  e:  1.8011
epoch [  300]  w[0]:  0.3310,  w[1]:  1.2926,  b:  0.9615,  e:  1.3159
epoch [  400]  w[0]:  0.1788,  w[1]:  1.1031,  b:  0.4265,  e:  0.9683
epoch [  500]  w[0]:  0.0846,  w[1]:  0.9611,  b:  0.0011,  e:  0.7559
epoch [  600]  w[0]:  0.0437,  w[1]:  0.8692,  b: -0.3237,  e:  0.6386
epoch [  700]  w[0]:  0.0426,  w[1]:  0.8188,  b: -0.5711,  e:  0.5741
epoch [  800]  w[0]:  0.0681,  w[1]:  0.7985,  b: -0.7637,  e:  0.5355
epoch [  900]  w[0]:  0.1105,  w[1]:  0.7987,  b: -0.9187,  e:  0.5095
epoch [ 1000]  w[0]:  0.1633,  w[1]:  0.8126,  b: -1.0477,  e:  0.4898
epoch [ 1100]  w[0]:  0.2222,  w[1]:  0.8356,  b: -1.1587,  e:  0.4735
epoch [ 1200]  w[0]:  0.2843,  w[1]:  0.8644,  b: -1.2569,  e:  0.4591
epoch [ 1300]  w[0]:  0.3480,  w[1]:  0.8969,  b: -1.3458,  e:  0.4461
epoch [ 1400]  w[0]:  0.4119,  w[1]:  0.9317,  b: -1.4278,  e:  0.4340
epoch 

In [6]:
prediction = sigmoid(np.dot(X,w)+b)
prediction

array([[0.00864305],
       [0.15201734],
       [0.1501691 ],
       [0.7841774 ]], dtype=float32)

In [7]:
predicted = tf.cast(prediction > 0.5, dtype=tf.float32) # 0, 1변환
result = tf.equal(predicted, y)  # output 과 같은지 참 거짓 변환
result

<tf.Tensor: id=3, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [8]:
accuracy = tf.reduce_mean(tf.cast(result, dtype=tf.float32))   # 참 거짓을 다시 수치로 변환하여 평균내서 정확도 계산
accuracy.numpy()

1.0

In [12]:
arr1 = np.array([[0, 0]], dtype="float32")
arr2 = np.array([[0, 1]], dtype="float32")
arr3 = np.array([[1, 0]], dtype="float32")
arr4 = np.array([[1, 1]], dtype="float32")

p1 = sigmoid(np.dot(arr1,w) + b)
p2 = sigmoid(np.dot(arr2,w) + b)
p3 = sigmoid(np.dot(arr3,w) + b)
p4 = sigmoid(np.dot(arr4,w) + b)

p11 = tf.cast(p1 > 0.5, dtype = tf.float32)
p22 = tf.cast(p2 > 0.5, dtype = tf.float32)
p33 = tf.cast(p3 > 0.5, dtype = tf.float32)
p44 = tf.cast(p4 > 0.5, dtype = tf.float32)

re = np.array([])
re = np.append(re, p11)
re = np.append(re, p22)
re = np.append(re, p33)
re = np.append(re, p44)
re

array([0., 0., 0., 1.])